CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    id_req_res INTEGER NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);
